### ISSUE TITLE
Ask for datasets

### ISSUE THREAD

**Issue by hh23333** [X-BrainLab/PI-ReID#11]
Hello, I sent an email to your Google Email to ask for the dataset three days ago, but I haven't received the reply yet. Could you please check your email? Thanks

**Comment by X-BrainLab** [comment]
Sorry, I didn’t receive your email.
You can send me again.

hh23333 ***@***.***>于2022年5月20日 周五16:07写道：

**Comment by hh23333** [comment]
Hi，
I used the edu email to ask for the datasets, and I have already received your reply. Thank you very much!
